# Generated by Django 2.1.5 on 2020-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDS', '0002_auto_20200403_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Name',
            field=models.TextField(max_length=20),
        ),
    ]
